patch:
  - head-branch: ['*patch*']

minor:
  - head-branch: ['*minor*']

major:
  - head-branch: ['*major*']

  

dockerfile-change:
  - changed-files:
      - any-glob-to-any-file: 'Dockerfile*'

alpine-dockerfile-change:
  - changed-files:
      - any-glob-to-any-file: 'alpine/Dockerfile'